### ISSUE TITLE
OpenApiGenerator is not a function after upgrading to 5.0.0 from 4.8.0

### ISSUE THREAD

**Issue by callmeberzerker** [asteasolutions/zod-to-openapi#147]
The error output looks like this. Any solutions?

`TypeError: zod_to_openapi_1.OpenAPIGenerator is not a constructor`

**Comment by AGalabov** [comment]
Hey @callmeberzerker - please take a look at the [release notes](https://github.com/asteasolutions/zod-to-openapi/releases/tag/v5.0.0). Overall there is no  `OpenAPIGenerator` - there are `OpenAPIGeneratorV3` and `OpenAPIGeneratorV31`
